name: Fly Deploy

on:
  push:
    branches:
      - main # change to main if needed

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Adjust this to your project's Node.js version
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Adjust this to your preferred pnpm version
      
      - name: Install dependencies
        run: pnpm install
        
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly.io
        run: |
          fly secrets set --stage ACCOUNT_ID=${{ secrets.ACCOUNT_ID }} ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }} SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }} MONGO_URI=${{ secrets.MONGO_URI }} WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }} EMAIL_HOST=${{ secrets.EMAIL_HOST }} EMAIL_PORT=${{ secrets.EMAIL_PORT }} EMAIL_USER=${{ secrets.EMAIL_USER }} EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} EMAIL_FROM=${{ secrets.EMAIL_FROM }} EMAIL_SECURE=${{ secrets.EMAIL_SECURE }} FRONTEND_DOMAIN=${{ secrets.FRONTEND_DOMAIN }} BACKEND_URL=${{ secrets.BACKEND_URL }}
          pnpm build
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
